version: '3.8'
services:
  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=diagramming_app
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/diagramming_app --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URL=mongodb://mongodb:27017
      - DATABASE_NAME=diagramming_app
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-this-in-production}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
    depends_on:
      - backend

volumes:
  mongodb_data:
